#!/bin/bash
set -e
NAME="$1"
PROJECT="$2"
TAG="$3"

# Run the builder script and attach to view output
ID=$(docker run -d -v $PROJECT:/app progrium/buildstep /build/builder)
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $NAME $TAG > /dev/null
